<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\licenses.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.8" />
        <PackageReference Include="HotAvalonia" Version="3.0.0" PrivateAssets="All" Publish="True" />
        <PackageReference Include="Avalonia" Version="11.2.8" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.8">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="DryIoc.dll" Version="5.4.3" />
        <PackageReference Include="Projektanker.Icons.Avalonia.FontAwesome" Version="9.6.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.0-preview.1.2" />
        <PackageReference Include="SukiUI" Version="6.1.3-preview" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\MainWindow.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Properties\licenses.json" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dawn.Core\Dawn.Core.csproj" />
    </ItemGroup>
</Project>
