//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("Dawn")]
[assembly: AssemblyCopyright("© 2025 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]17.04.2025 16:44:04")]
[assembly: AssemblyMetadata("Branch", "avalonia_version")]
[assembly: AssemblyMetadata("Commit", "a3ebbda40f0d2a5ec9d45200b9f65aef81cc0fd0")]
[assembly: AssemblyMetadata("Version", "2.2.68-ga3ebbda40f")]
