//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("Dawn")]
[assembly: AssemblyCopyright("© 2023 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]17.12.2023 16:05:13")]
[assembly: AssemblyMetadata("Branch", "dev")]
[assembly: AssemblyMetadata("Commit", "c9adab1e9c1d01844163697ab11f82f0249d3105")]
[assembly: AssemblyMetadata("Version", "2.2.46-gc9adab1e9c")]
