//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("Dawn")]
[assembly: AssemblyCopyright("© 2025 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]12.04.2025 07:14:32")]
[assembly: AssemblyMetadata("Branch", "avalonia_version")]
[assembly: AssemblyMetadata("Commit", "c5d70bfa10d1f374973f4de574e8e22e33e6605f")]
[assembly: AssemblyMetadata("Version", "2.2.61-gc5d70bfa10")]
